### PR TITLE
next: Adds options parameter

### PR DESCRIPTION
**Pull request by lizell**
Adds options parameter to the CALL_API which is passed to the underlying fetch call. This allows us to control things like network timeouts and redirects, etc.

Example:

``` js
{
  [CALL_API]: {
    ...
    options: { timeout: 3000 }
    ...
  }
}
```

This is somewhat different than #79 that adds the possible options directly on the `CALL_API`.

This replaces #101 that was the same thing but for `1.x`.

### CODE REVIEW

**Comment by lizell** [comment]
Great! 😄

**Comment by mucsi96** [comment]
@nason Can I kindly ask to release this? please :)

**Comment by nason** [comment]
@mucsi96 sorry, this one slipped away.

Released in `2.0.0-beta.4`

**Comment by mucsi96** [comment]
@nason Thank you so much! 🍰  Can I help with anything to merge `next` to `master` and release a stable version?

**Comment by nason** [comment]
@mucsi96 thanks for the offer 💛 ! I finally found some time and cut the 2.0 release.

Please let us know if you run into any issues!

**Pull request merged**
