### PR TITLE
Add action creator for RSAA action

### PR DESCRIPTION
**Pull request by artursvonda**
Created action creator for cleaner boundary for RSAA actions.
This abstracts shape of the action away from user and allows. And it allows to add validation to action creation process if we choose to (which can be dev build only thing).

This will also allow for nicer and cleaner typings for Typescript.

### CODE REVIEW

**Comment by nason** [comment]
Hi @artursvonda, thanks for the contribution! This looks reasonable.

Would you mind adding some documentation about this?

**Comment by artursvonda** [comment]
> Hi @artursvonda, thanks for the contribution! This looks reasonable.
> 
> Would you mind adding some documentation about this?

Will do

**Comment by artursvonda** [comment]
Rewrote docs to use `createAction` as the preferred way to create RSAA actions.

**Comment by iamandrewluca** [comment]
Should `RSAA` be marked with some JsDoc annotation? Like `@access private` or `@deprecated` to discourage it's use?

**Comment by artursvonda** [comment]
> Should `RSAA` be marked with some JsDoc annotation? Like `@private` or `@deprecated` to discourage it's usage?

Yeah, makes sense. Will add that. If we want to remove the export in some future version, we should `@deprecated` to indicate that it be removed. If we want to keep it there but discourage, `@private` makes sense.

I think it makes sense to remove it as long as all use-cases are handled without it. And the only use-case I can think of, that is not yet handled, is getting options from action. But that can be added later if required.

**Comment by artursvonda** [comment]
Done

**Comment by nason** [comment]
Thank you @artursvonda!

I'm going to merge and release this as `3.2.0` as soon as I have a chance, tonight or tomorrow.

**Comment by artursvonda** [comment]
Reminder to merge and release this :)

**Comment by nason** [comment]
My bad @artursvonda! So sorry for the delay. I will ship this after after work today!

**Pull request merged**
