### PR TITLE
resolve body with redux state when body is a function

### PR DESCRIPTION
**Pull request by tungv**
similar to get and headers

### CODE REVIEW

**Comment by luisincrespo** [comment]
+1

**Comment by IanLondon** [comment]
+1 what's happening with this?

**Comment by tungv** [comment]
I ended up writing my own lib: https://npm.im/redux-api-call

**Comment by ztanner** [comment]
It's not pretty, but if you want to avoid forking this or using a different library, you can write your own middleware that extends CALL_API. ex:

```js
const withStateMiddleware = store => next => action => {
  if (CALL_API in action && typeof action[CALL_API].body === 'function') {
    return next({
      ...action,
      [CALL_API]: {
        ...action[CALL_API],
        body: action[CALL_API].body(store.getState)
      }
    });
  }
  return next(action);
};
```

Then your body key can just be:
```js
body: getState => { ... }
```
Would be nice to get this merged though.

**Comment by nason** [comment]
Hi @tungv, thanks for this and sorry its taken so long to get to 😿 

This is pretty interesting functionality. `master` is currently the 1.0 branch, and we're working on 2.0 in `next`.

To get this in, we'd need to target this change to the `next` branch. Do you still want to help? I might be able to work on this in a couple days otherwise.

**Comment by nason** [comment]
Hi @tungv I went ahead and ported this change over to 2.x in https://github.com/agraboso/redux-api-middleware/pull/168

Thank you!

**Pull request closed without merging**
