### PR TITLE
Changed FSA type dispatched on network errors to failureType

### PR DESCRIPTION
**Pull request by sgoll**
Please see issue #25 for the rationale behind this pull request.

Basically, we want to make sure that the following invariant always holds true: for each `[CALL_API]` action that is handled by `redux-api-middleware`,
- exactly one `request` FSA is dispatched, and
- that `request` FSA is followed by either:
  - nothing (when the _request_ FSA had its `error` property set), or
  - either a single `success` FSA or a single `failure` FSA (when the _request_ FSA had its `error` property unset).

The actual code change is literally a single line, but the accompanying documentation change is rather more elaborate and might require some review.

Also, since the third argument `res` might now be either present or absent from the `failure` type descriptor's custom `payload` and `meta` properties (when using functions), this change is not backward compatible.

### CODE REVIEW

**Comment by barrystaes** [comment]
I agree with your point.
There should be only 1 `request` and errors should be in a `failure` FSA.
And since this touches functionality i'd like @agraboso to give a green light for merging.

About the implementation;
- I dont really understand the "res" sidenote you end with. 
- Should we do the same for [the FSA resulting from a bailout](https://github.com/agraboso/redux-api-middleware/blob/cd1a28a992542b3024d987b53e8b46ca210ae15b/src/middleware.js#L46-L61) which also used the `requestType`?
- Are there more places `requestType` is used to return errors?
- There is a merge conflict in this PR. Could you rebase it to the latest version?

**Comment by sgoll** [comment]
I updated the pull request.

@barrystaes:

Previously the following invariant was true: when the `failure` type descriptor defines custom `payload` and `meta` functions, those are called with three arguments: `(action, state, res)`. With the changes done in this PR, this is no longer true: `res` might not be available when issuing a `failure` FSA, i.e. those functions might receive `res === undefined`. This may or may not be a problem.

Regarding your first question: I think it is okay to bail out with an error'd `request` FSA. The motivation for this issue was only that there could be *multiple* `request` FSAs. However, when the (only) `request` FSA received is marked as error that would be okay with me. It's only the two `request` FSAs (first without error, second with error) that I have a problem with and which should be fixed by this PR.

**Comment by barrystaes** [comment]
Better late than never: thank you for the PR update.
Ok i now understand this is not about the request FSA with error flag.

Since this -as i understand- in principle is a breaking change, i now realize this PR should go to the `next` v2.0.0-beta branch instead of a v1.1.x release. @sgoll what do you think? Also, i wonder i you/anyone uses these changes in production?

**Comment by johnwiseheart** [comment]
Any update on this?

**Comment by nason** [comment]
This will be changed in #175

**Pull request closed without merging**
